### ISSUE TITLE
Can't get basic autocomplete from crate (non-Git)

### ISSUE THREAD

**Issue by bruno-medeiros** [phildawes/racer#642]
So I have this code:
```rust
extern crate serde_json;

use serde_json::Value;

fn main() {
    let x = Value::Null;
}
```
with Cargo.toml:

```toml
[package]
name = "hello_world"
version = "0.0.1"

[dependencies]
serde = "0.8.0"
serde_json = "0.8"
```

And I don't seem to get any completion nor find-definition related to serde_json, Value, etc..

Happens with either latest racer from master or from crates.io . Is this case supposed to work? I think it used to work some time ago, but I'm not sure.
